# Generated by Django 3.2.25 on 2024-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
